#!/usr/bin/env node

'use strict';
var c = require('skilstak-colors')

var  printPlain = function (message) {
  console.log(message);
}

function printBlue(message) {
  console.log(c.blue + (message) + c.x);
}

var printRed = function(message) {
  console.log(c.red + (message) + c.x);
}

var printMulti = function (message) {
  while(true) {
    console.log(c.clear + c.multi(message));
  }
}

var firstValue = process.argv[2]



//printPlain("Hello");
//printMulti("Hello");
printBlue("Hello " + firstValue);
//printRed("Hey");

